version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev  
      - DB_HOST=localhost         
      - DB_USER=root        
      - DB_PASSWORD=root     
      - DB_NAME=groceries_information  
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: groceries_information
